export const patternHistoryArray = [
  {
    date: [Object],
    drillId: 'Up Down',
    misses: {
      bottomLeft: 3,
      bottomRight: 0,
      fiveHole: 0,
      leftShoulder: 2,
      middleLeft: 0,
      middleRight: 0,
      rightShoulder: 0,
      topLeft: 0,
      topRight: 2,
      underBlocker: 0,
      underGlove: 0,
    },
    shooter: {
      age: '24',
      dateCreated: [st],
      displayName: 'Gabe',
      email: 'gabe@gabe.com',
      uid: 'JkffQOz9IlhWPndYTTvINTl8A0n2',
    },
    totalMisses: 7,
  },
  {
    date: [Object],
    drillId: 'Dump and Chase',
    misses: {
      bottomLeft: 0,
      bottomRight: 3,
      fiveHole: 0,
      leftShoulder: 0,
      middleLeft: 0,
      middleRight: 0,
      rightShoulder: 0,
      topLeft: 1,
      topRight: 0,
      underBlocker: 0,
      underGlove: 0,
    },
    shooter: {
      age: '24',
      dateCreated: [st],
      displayName: 'Gabe',
      email: 'gabe@gabe.com',
      uid: 'JkffQOz9IlhWPndYTTvINTl8A0n2',
    },
    totalMisses: 4,
  },
  {
    date: [Object],
    drillId: 'The Frustrating One',
    misses: {
      bottomLeft: 0,
      bottomRight: 0,
      fiveHole: 1,
      leftShoulder: 0,
      middleLeft: 0,
      middleRight: 0,
      rightShoulder: 0,
      topLeft: 1,
      topRight: 1,
      underBlocker: 0,
      underGlove: 0,
    },
    shooter: {
      age: '24',
      dateCreated: [st],
      displayName: 'Gabe',
      email: 'gabe@gabe.com',
      uid: 'JkffQOz9IlhWPndYTTvINTl8A0n2',
    },
  },
  {
    date: [Object],
    drillId: 'The Frustrating One',
    misses: {
      bottomLeft: 0,
      bottomRight: 0,
      fiveHole: 0,
      leftShoulder: 0,
      middleLeft: 0,
      middleRight: 0,
      rightShoulder: 0,
      topLeft: 1,
      topRight: 0,
      underBlocker: 2,
      underGlove: 0,
    },
    shooter: {
      age: '24',
      dateCreated: [st],
      displayName: 'Gabe',
      email: 'gabe@gabe.com',
      uid: 'JkffQOz9IlhWPndYTTvINTl8A0n2',
    },
    totalMisses: 3,
  },
  {
    date: [Object],
    drillId: 'Downtown',
    misses: {
      bottomLeft: 3,
      bottomRight: 0,
      fiveHole: 0,
      leftShoulder: 0,
      middleLeft: 0,
      middleRight: 0,
      rightShoulder: 0,
      topLeft: 2,
      topRight: 0,
      underBlocker: 0,
      underGlove: 0,
    },
    shooter: {
      age: '24',
      dateCreated: [st],
      displayName: 'Gabe',
      email: 'gabe@gabe.com',
      uid: 'JkffQOz9IlhWPndYTTvINTl8A0n2',
    },
  },
  {
    date: [Object],
    drillId: 'Around the World',
    misses: {
      bottomLeft: 0,
      bottomRight: 0,
      fiveHole: 0,
      leftShoulder: 0,
      middleLeft: 0,
      middleRight: 0,
      rightShoulder: 0,
      topLeft: 1,
      topRight: 0,
      underBlocker: 2,
      underGlove: 0,
    },
    shooter: {
      age: '24',
      dateCreated: [st],
      displayName: 'Gabe',
      email: 'gabe@gabe.com',
      uid: 'JkffQOz9IlhWPndYTTvINTl8A0n2',
    },
  },
];
